name = "CP"
version = "1.0"
extra_files = "extras"
intro = "src/introc.lean"


[[worlds]]
name = "Goldbach"
id = 1
levels = [ "src/tutorial/tutorialc.lean",
             ]

[[worlds]]
name = "Collatz"
id = 2
levels = [ "src/tutorial/collatz.lean",
             ]
