# Sample workflow for building and deploying a site to GitHub Pages
name: Build and Deploy The Euclid Game site to Pages
# Controls when the workflow will run
on:
  # Runs on pushes targeting the default branch
  push:
    branches: [$default-branch]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

# Default to bash
defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    env: 
      branch: 'main'
      source_base_url: "https://raw.githubusercontent.com/${{ github.repository }}/main/"
      # web_editor_url: "https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/editor"

    steps:
      - name: Echo branch
        run: |
          echo Deploying branch: $branch
          echo Source base url: $source_base_url
          echo Web editor url: $web_editor_url
      - name: Checkout main branch
        uses: actions/checkout@v2
        with:
          ref: ${{ env.branch }}
  
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10.4'

      - name: Update packages
        run: sudo apt install -y unzip make nodejs gettext build-essential libssl-dev zlib1g-dev libbz2-dev libreadline-dev libsqlite3-dev wget curl llvm libncurses5-dev libncursesw5-dev xz-utils tk-dev libffi-dev liblzma-dev python3-openssl
 
      - name: Install elan
        run: |
          set -o pipefail
          curl https://raw.githubusercontent.com/leanprover/elan/master/elan-init.sh -sSf | sh -s -- -v -y
          sudo ln -s $HOME/.elan/bin/* /usr/local/bin;
          
      - name: Install python Lean dependencies
        run: |
          python -m pip install --upgrade pip requests markdown2 toml mathlibtools toposort invoke
      - name: upgrade Lean and dependencies
        uses: leanprover-contrib/lean-upgrade-action@master
        with:
          repo: ${{ github.repository }}
          access-token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: leanpkg configure
        run: leanpkg configure

      - name: get mathlib cache
        run: leanproject get-mathlib-cache || true

      - name: leanpkg build
        id: build
        run: |
          echo "::set-output name=started::true"
          lean --json --make src | python scripts/detect_errors.py
          lean --json --make src | python scripts/detect_errors.py

      - name: Install Game maker
        run: |
          git clone --depth=1 https://github.com/mmasdeu/Lean-game-maker.git
          cd Lean-game-maker/src/interactive_interface
          npm install .
          ./node_modules/.bin/webpack --mode=production
          cd ../..
          pip3 install -e .
          
      - name : Get server files
        run: |
          curl -s https://api.github.com/repos/leanprover-community/lean/releases/latest | grep "browser.zip" | grep -v name | cut -d : -f 2,3 | tr -d \"  | wget -qi -
          unzip *.zip
          LATEST_BROWSER_LEAN=`ls *zip | cut -c 6-11`
          echo "LATEST_BROWSER_LEAN=$LATEST_BROWSER_LEAN" >> $GITHUB_ENV
          mkdir -p "Lean-game-maker/src/interactive_interface/lean_server/leanprover-community/lean:$LATEST_BROWSER_LEAN/"
          cp build/shell/* "Lean-game-maker/src/interactive_interface/lean_server/leanprover-community/lean:$LATEST_BROWSER_LEAN/"
          
      - name: Make game
        run: |
          cat leanpkg.path
          make-lean-game --source_base_url=$source_base_url --web_editor_url=$web_editor_url
          
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          # Upload ./html files: 
          path: './html'
 
  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
